spring.application.name=projeto-semestre
spring.datasource.url=jdbc:postgresql://db.zujsihtvrqastoaifwcm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=OpbzrOFVXPOhgCEB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true